apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: famflix-cluster
  region: ap-southeast-2
  version: "1.34"

availabilityZones:
  - ap-southeast-2a
  - ap-southeast-2b

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false
