apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: famflix
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: famflix-backend-ingress
  namespace: famflix
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: famflix-strip-api-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: famflix.cc
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

    - host: www.famflix.cc
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
